#!/bin/bash

curl -O https://www.antlr.org/download/antlr-4.7.1-complete.jar
java -cp antlr-4.7.1-complete.jar org.antlr.v4.Tool -package com.oracle.truffle.wasm.parser -no-listener language/src/main/java/com/oracle/truffle/wasm/parser/WasmLanguage.g4
